# Organização de Vídeos ICT 2019-2020

## Inicialização

In [1]:
# Incluindo diretório scripts no caminho
from glob import glob
import sys
import os
sys.path.insert(0, './DATA/')

In [2]:
# show result from all calculations of the cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
# pacotes básicos
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('max_colwidth',250)
import unidecode
import re
import argparse
from argparse import Namespace

## Testando Integridade dos dados

In [4]:
import videolist as vd

In [21]:
tipo = Namespace(type='UA')

In [29]:
df1 = vd.do_list()
df_sel = vd.do_subset(df1,tipo)

In [30]:
videos_validos = df1
listas = ['CENTRO','UA','AREA']
categorias = [videos_validos[el].unique().tolist() for el in listas]
playlists = [ videos_validos[ videos_validos[el] == categ ]['ID']
    for el in listas for categ in categorias[listas.index(el)] ]
df = pd.DataFrame(columns = column_names)
POS = 0
for item in listas:
    for item2 in categorias[listas.index(item)]:
        df.loc[len(df)] = [item, item2, videos_validos[videos_validos.index.isin(playlists[POS].index)]]
        POS += 1
df

,TIPO,CRITERIO,DADOS
0,CENTRO,CSTR,ID \ 46 7733 18 7510 127 7875 157 7966 158 7970 159 7974 74 7708 119 7872 52 7639 134 8054 153 7963 155 7964 9 7500 122 7740 88 7776 43 7617 133 7887 84 7840 ...
1,CENTRO,CCT,ID \ 213 7553 95 7817 1 7479 140 7922 16 7508 86 7773 195 8107 38 7596 2 7481 85 7762 212 8043 115 7868 152 7951 175 8011 8 7499 90 7810 209 8193 76 7715 ...
2,CENTRO,CDSA,ID \ 160 7967 64 7674 75 7713 ...
3,CENTRO,CH,ID \ 91 7811 177 8021 78 7717 14 7505 70 7691 58 7657 187 8078 170 8003 72 7695 202 8138 15 7612 172 8007 173 8048 30 7585 63 7668 166 7989 186 8068 ...
4,CENTRO,CTRN,ID \ 106 7838 26 7558 28 7572 34 7590 35 7607 3 7486 174 8008 7 7491 210 8192 109 7850 4 7512 37 7591 216 7735 25 7557 62 7662 24 7552 97 7822 98 7861 ...
...,...,...,...
91,AREA,AGRONOMIA,ID \ 206 8171 TITULO \ 206 MORFOLOGIA E FISIOLOGIA DE ACESSOS DE FEIJÃO-FAVA (PHASEOLUS LUNATUS L.)...
92,AREA,NUTRIÇÃO,ID \ 203 8155 204 8164 214 7863 TITULO \ 203 AVALIAÇÃO DO COMPORTAMENTO DO C...
93,AREA,CIÊNCIA POLÍTICA,ID \ 30 7585 TITULO \ 30 POLÍTICA E RELIGIÃO: UMA PESQUISA NETNOGRÁFICA SOBRE A RELAÇÃO DOS CRISTÃOS COM A DEMOCRACIA DOCENTE CEN...
94,AREA,BIOQUÍMICA,ID \ 201 8133 TITULO \ 201 ADESÃO AO TRATAMENTO DO PACIENTE DIABÉTICO EM UNIDADE BÁSICA DE SAÚDE DE CAJAZEIRAS-PB DOC...
95,AREA,MORFOLOGIA,ID \ 83 7793 TITULO \ 83 ANATOMIA DO APARELHO REPRODUTOR DOS SAGUIS-DE-TUFOS-BRANCOS (CALLITHRIX JACCHUS) DOCENTE CENTRO UA ...